name: Beta Release

on:
  push:
    branches: [beta]
  workflow_dispatch:

jobs:
  release:
    uses: Conduction/.github/.forgejo/workflows/release-semrel-beta.yml@main
    with:
      app-name: zaakafhandelapp
    secrets: inherit
