name: Stable Release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: ConductionNL/.github/.github/workflows/release-stable.yml@main
    with:
      app-name: zaakafhandelapp
    secrets: inherit
